#这是文件上传模块,需要注册进入eureka...
#这是文件上传模块,需要注册进入eureka...
#这是文件上传模块,需要注册进入eureka...
#这是文件上传模块,需要注册进入eureka...
server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
# Eureka
eureka:
  client:
    #注册进入eureka容器
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #将zuul注册到eureka集群
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 15 # 15秒不发送就过期
