#这是eureka注册中心...
#这是eureka注册中心...
#这是eureka注册中心...

#我就是容器,你们都来注册
#我就是容器,你们都来注册
#我就是容器,你们都来注册

server:
  port: 10086
spring:
  application:
    name: leyou-register
eureka:
  client:
    register-with-eureka: false #把自己注册到eureka服务列表
    fetch-registry: false #拉取eureka服务信息
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
  server:
    enable-self-preservation: false # 关闭自我保护
    eviction-interval-timer-in-ms: 10000 # 每隔10秒钟，进行一次服务列表的清理




#这里引入的是
#spring-cloud-starter-netflix-eureka-server
#    <dependencies>
#        <dependency>
#            <groupId>org.springframework.cloud</groupId>
#            <artifactId>spring-cloud-starter-netflix-eureka-server</artifactId>
#        </dependency>
#    </dependencies>